config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :classrooms
  resources :salarypayments
  resources :feepayments
  resources :salaries
  resources :tuitionfees
  resources :users

  root 'welcome#home'
  # root 'welcome#login'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  
  # get '/auth/github/callback' => 'sessions#create'

  # get '/auth/developer/callback' => 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/salary.rb
class Salary < ApplicationRecord
    has_many :teachers

    def to_s
        return self.salary_code
    end

end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController

    def index
		@salaries = Salary.all
	end

    def new
        @salary = Salary.new
    end
  
    def create
        @salary = Salary.new(salary_params)
        if @salary.save
        redirect_to salary_path(@salary)
       else
        render :new
       end
    end
  
    def show
        @salary = Salary.find(params[:id])
    end
  
     
    def edit
        @salary = Salary.find(params[:id])
    end
  
    def update
        @salary = Salary.find(params[:id])
        if @salary.update(salary_params)
        redirect_to salary_path(@salary)
        else
            render :edit
        end
    end

    def destroy
        Salary.find(params[:id]).destroy
        redirect_to action: "index"
    end
  
    private
  
    def salary_params
        params.require(:salary).permit(:id, :salary_code, :fortnightly_salary)
    end  

end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/edit.html.erb
    <%= render "layouts/header" %>  

<div class="center">

<h1>Updating a SALARY Category</h1>
<%= form_for(@salary) do |f| %>
  <label>Salary Code:</label><br>
  <%= f.text_field :salary_code %><br>

  <label>Fortnightly Salary</label><br>
  <%= f.text_area :fortnightly_salary %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/salaries/index.html.erb
    <%= render "layouts/header" %>  

  <h1 class="center">All Salary Categories</h1>

  <div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>SALARY ID</th>
            <th>SALARY CODE</th>
            <th>FORTNIGHTLY SALARY</th>
            <th>DETAILS/UPDATE/DELETE</th>
        </tr>
      </thead>
      <tbody>
        <% @salaries.each do |amount| %>
          <tr>
            <td><%= amount.id %></td>
            <td><%= amount.salary_code %></td>
            <td><%= amount.fortnightly_salary %></td>
            <td><%= link_to "DETAILS/UPDATE/DELETE", salary_path(amount) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
<br>
<table class="center">
      <thead>
        <tr>
          <th><%= link_to "+ Create Salary Category", new_salary_path %></th>
        </tr>
      </thead>
</table>

app/views/salaries/new.html.erb
    <%= render "layouts/header" %>  
<div class="center">

<h1>Creating a NEW SALARY Category</h1>
<%= form_for(@salary) do |f| %>
  <label>Salary ID:</label><br>
  <%= f.text_field :id %><br>

  <label>Salary Code:</label><br>
  <%= f.text_field :salary_code %><br>

  <label>Fortnightly Salary</label><br>
  <%= f.text_area :fortnightly_salary %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/salaries/show.html.erb
    <%= render "layouts/header" %>  

<h3 class="center"> FOLLOWING ARE THE DETAILS OF SALARY CATEGORY "<%= @salary.salary_code %>"</h3>

<div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>DESCRIPTION</th>
            <th>VALUE</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>CODE OF THIS SALARY CATEGORY:</td>
            <td><%= @salary.salary_code %></td>
          </tr>
          <tr>
          <td>FORTNIGHTLY SALARY AMOUNT:</td>
          <td><%= @salary.fortnightly_salary %></td>
          </tr>
      </tbody>
    </table>
  </div>
  <br>
  <br>

<table class="center">
      <thead>
        <tr>
            <th><%= link_to "DELETE", @salary, method: :delete, data: { confirm: "Really want to DELETE the TuitionFee category #{@salary.to_s}?" } %></th>
            <th><%= link_to "UPDATE", edit_salary_path(@salary) %></th>
            <th><%= link_to "BACK", salaries_path %></th>
        </tr>
      </thead>
</table>