config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :classrooms
  resources :salarypayments
  resources :feepayments
  resources :salaries
  resources :tuitionfees
  resources :users

  root 'welcome#home'
  # root 'welcome#login'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  
  # get '/auth/github/callback' => 'sessions#create'

  # get '/auth/developer/callback' => 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :salary
  has_many :classrooms
  has_many :students, through: :classrooms

  def to_s
    return self.teacher_name
  end

  def salary_category
    self.salary.salary_code
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

    def index
		@teachers = Teacher.all
	end

    def new
        @teacher = Teacher.new
    end
  
    def create
        @teacher = Teacher.new(teacher_params)
        if @teacher.save
        redirect_to teacher_path(@teacher)
       else
        render :new
       end
    end
  
    def show
        @teacher = Teacher.find(params[:id])
    end
  
     
    def edit
        @teacher = Teacher.find(params[:id])
    end
  
    def update
        @teacher = Teacher.find(params[:id])
        if @teacher.update(teacher_params)
        redirect_to teacher_path(@teacher)
        else
            render :edit
        end
    end

    def destroy
        Teacher.find(params[:id]).destroy
        redirect_to action: "index"
    end
  
    private
  
    def teacher_params
        params.require(:teacher).permit(:id, :teacher_code, :teacher_name, :teacher_email, :teacher_homeaddress, :teacher_mobile_number, :teacher_gender, :engagement_date, :teacher_bankdetails, :salary_id)
    end

    def salary_params
        params.require(:salary).permit(:salary_id)
    end  

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
    <%= render "layouts/header" %>  

<div class="center">

<h1>Updating a TEACHER DATA</h1>
<%= form_for(@teacher) do |f| %>
  <label>Teacher Code:</label><br>
  <%= f.text_field :teacher_code %><br>

  <label>Name of Teacher</label><br>
  <%= f.text_area :teacher_name %><br>

  <label>Teacher's Email ID</label><br>
  <%= f.text_area :teacher_email %><br>

  <label>Teacher's Home Address</label><br>
  <%= f.text_area :teacher_homeaddress %><br>

  <label>Teacher's Mobile Number</label><br>
  <%= f.text_area :teacher_mobile_number %><br>

  <label>Teacher's Gender</label><br>
  <%= f.text_area :teacher_gender %><br>

  <label>Teacher's Engagement Date</label><br>
  <%= f.text_area :engagement_date %><br>

  <label>Teacher's Bank Details</label><br>
  <%= f.text_area :teacher_bankdetails %><br>

  <label>Salary Code of the Teacher</label><br>
  <%= f.collection_select :salary, Salary.all, :id, :salary_code, { include_blank: false }, { class: "collectionselect" } %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/teachers/index.html.erb
    <%= render "layouts/header" %>    
  
  <h1 class="center">All Teacher's Data</h1>

  <div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>TEACHER ID</th>
            <th>TEACHER CODE</th>
            <th>TEACHER's NAME</th>
            <th>TEACHER's EMAIL</th>
            <th>TEACHER's HOME ADDRESS</th>
            <th>TEACHER's MOBILE NUMBER</th>
            <th>TEACHER's GENDER</th>
            <th>ENGAGEMENT DATE</th> 
            <th>TEACHER's BANKDETAILS</th>
            <th>TEACHER's SALARY CODE</th>
            <th>DETAILS/UPDATE/DELETE</th>
        </tr>
      </thead>
      <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= teacher.id %></td>
            <td><%= teacher.teacher_code %></td>
            <td><%= teacher.teacher_name %></td>
            <td><%= teacher.teacher_email %></td>
            <td><%= teacher.teacher_homeaddress %></td>
            <td><%= teacher.teacher_mobile_number %></td>
            <td><%= teacher.teacher_gender %></td>
            <td><%= teacher.engagement_date %></td>
            <td><%= teacher.teacher_bankdetails %></td>
            <td><%= teacher.salary_category %></td>
            <td><%= link_to "DETAILS/UPDATE/DELETE", teacher_path(teacher) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
<br>
<table class="center">
      <thead>
        <tr>
          <th><%= link_to "+ Create a Teacher Data", new_teacher_path %></th>
        </tr>
      </thead>
</table>

app/views/teachers/new.html.erb
    <%= render "layouts/header" %>  

<div class="center">

<h1>Creating a NEW TEACHER DATA</h1>
<%= form_for(@teacher) do |f| %>
  <label>Teacher Code:</label><br>
  <%= f.text_area :teacher_code, placeholder: "TC202" %><br>

  <label>Name of Teacher</label><br>
  <%= f.text_area :teacher_name, placeholder: "Michael Brent" %><br>

  <label>Teacher's Email ID</label><br>
  <%= f.text_area :teacher_email, placeholder: "brent@yahoo.com" %><br>

  <label>Teacher's Home Address</label><br>
  <%= f.text_area :teacher_homeaddress, placeholder: "31 Brent Street, Geelong, VIC-3220" %><br>

  <label>Teacher's Mobile Number</label><br>
  <%= f.text_area :teacher_mobile_number, placeholder: "0412356789" %><br>

  <label>Teacher's Gender</label><br>
  <%= f.text_area :teacher_gender, placeholder: "Male" %><br>

  <label>Teacher's Engagement Date</label><br>
  <%= f.text_area :engagement_date, placeholder: "01/10/2022" %><br>

  <label>Teacher's Bank Details</label><br>
  <%= f.text_area :teacher_bankdetails, placeholder: "BSB: 063-540 / ACC: 1048-3220" %><br>

  <label>Salary Code of the Teacher</label><br>
  <%= f.collection_select :salary, Salary.all, :id, :salary_code, { include_blank: false }, { class: "collectionselect" } %><br>

    <%= f.submit %>
<% end %>

</div>

app/views/teachers/show.html.erb
    <%= render "layouts/header" %>  

<h3 class="center"> FOLLOWING ARE THE DETAILS OF TEACHER "<%= @teacher.teacher_name %>"</h3>

<div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>DESCRIPTION</th>
            <th>VALUE</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>TEACHER CODE:</td>
            <td><%= @teacher.teacher_code %></td>
          </tr>
          <tr>
          <td>NAME OF TEACHER:</td>
          <td><%= @teacher.teacher_name.titleize %></td>
          </tr>
          <tr>
          <td>TEACHER's EMAIL ID:</td>
          <td><%= @teacher.teacher_email %></td>
          </tr>
          <tr>
          <td>TEACHER's HOME ADDRESS:</td>
          <td><%= @teacher.teacher_homeaddress %></td>
          </tr>
          <tr>
          <td>TEACHER's MOBILE NUMBER:</td>
          <td><%= @teacher.teacher_mobile_number %></td>
          </tr>
          <tr>
          <td>TEACHER's GENDER:</td>
          <td><%= @teacher.teacher_gender %></td>
          </tr>
          <tr>
          <td>TEACHER's ENGAGEMENT DATE:</td>
          <td><%= @teacher.engagement_date %></td>
          </tr>
          <tr>
          <td>TEACHER's BANK DETAILS:</td>
          <td><%= @teacher.teacher_bankdetails %></td>
          </tr>
          <tr>
          <td>TEACHER's SALARY CODE:</td>
          <td><%= @teacher.salary_category %></td>
          </tr>
      </tbody>
    </table>
  </div>
  <br>
  <br>

<table class="center">
      <thead>
        <tr>
            <th><%= link_to "DELETE", @teacher, method: :delete, data: { confirm: "Really want to DELETE the Teacher Data? #{@teacher.to_s}?" } %></th>
            <th><%= link_to "UPDATE", edit_teacher_path(@teacher) %></th>
            <th><%= link_to "BACK", teachers_path %></th>
        </tr>
      </thead>
</table>