config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :classrooms
  resources :salarypayments
  resources :feepayments
  resources :salaries
  resources :tuitionfees
  resources :users

  root 'welcome#home'
  # root 'welcome#login'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  
  # get '/auth/github/callback' => 'sessions#create'

  # get '/auth/developer/callback' => 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/feepayment.rb
class Feepayment < ApplicationRecord
  belongs_to :student

  def to_s
    return self.feepayment_code
  end

  def name_of_student
    self.student.student_name
  end

end

app/controllers/feepayments_controller.rb
class FeepaymentsController < ApplicationController

    def index
		@feepayments = Feepayment.all
	end

    def new
        @feepayment = Feepayment.new
    end
  
    def create
        # @feepayment = Feepayment.create(feepayment_params)
        # redirect_to feepayment_path(@feepayment)

        @feepayment = Feepayment.new(feepayment_params)
        if @feepayment.save
        redirect_to feepayment_path(@feepayment)
       else
        render :new
       end
    end
  
    def show
        @feepayment = Feepayment.find(params[:id])
    end
  
     
    def edit
        @feepayment = Feepayment.find(params[:id])
    end
  
    def update
        @feepayment = Feepayment.find(params[:id])
        if @feepayment.update(feepayment_params)
        redirect_to feepayment_path(@feepayment)
        else
            render :edit
        end
    end

    def destroy
        Feepayment.find(params[:id]).destroy
        redirect_to action: "index"
    end
  
    private
  
    def feepayment_params
        params.require(:feepayment).permit(:id, :feepayment_code, :date_of_payment, :amount_of_payment, :student_id)
    end

    def student_params
        params.require(:student).permit(:student_id)
    end

end

app/helpers/feepayments_helper.rb
module FeepaymentsHelper
end

app/views/feepayments/edit.html.erb
    <%= render "layouts/header" %>  

<div class="center">

<h1>Updating a Fee Payment</h1>
<%= form_for(@feepayment) do |f| %>
  <label>Fee Payment Code:</label><br>
  <%= f.text_field :feepayment_code %><br>

  <label>Date of Payment</label><br>
  <%= f.text_area :date_of_payment %><br>

  <label>Amount of Payment</label><br>
  <%= f.text_area :amount_of_payment %><br> 

    <label>Student Name</label><br>
  <%= f.collection_select :student, Student.all, :id, :student_name, { include_blank: false }, { class: "collectionselect" } %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/feepayments/index.html.erb
    <%= render "layouts/header" %>    
  
  <h1 class="center">All Fee Payment Records</h1>

  <div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>FEE PAYMENT ID</th>
            <th>FEE PAYMENT CODE</th>
            <th>DATE OF PAYMENT</th>
            <th>AMOUNT OF PAYMENT</th>
            <th>STUDENT NAME</th>         
            <th>DETAILS/UPDATE/DELETE</th>
        </tr>
      </thead>
      <tbody>
        <% @feepayments.each do |fee| %>
          <tr>
            <td><%= fee.id %></td>
            <td><%= fee.feepayment_code %></td>
            <td><%= fee.date_of_payment %></td>
            <td><%= fee.amount_of_payment %></td>
            <td><%= fee.name_of_student %></td>
            <td><%= link_to "DETAILS/UPDATE/DELETE", feepayment_path(fee) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
<br>
<table class="center">
      <thead>
        <tr>
          <th><%= link_to "+ Record a New Fee Payment", new_feepayment_path %></th>
        </tr>
      </thead>
</table>

app/views/feepayments/new.html.erb
    <%= render "layouts/header" %>  

<div class="center">

<h1>Creating a New Fee Payment</h1>
<%= form_for(@feepayment) do |f| %>
  <label>Fee Payment Code:</label><br>
  <%= f.text_field :feepayment_code %><br>

  <label>Date of Payment</label><br>
  <%= f.text_area :date_of_payment %><br>

  <label>Amount of Payment</label><br>
  <%= f.text_area :amount_of_payment %><br> 

    <label>Student Name</label><br>
  <%= f.collection_select :student, Student.all, :id, :student_name, { include_blank: false }, { class: "collectionselect" } %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/feepayments/show.html.erb
    <%= render "layouts/header" %>  

<h3 class="center"> FOLLOWING ARE THE DETAILS OF FEE PAYMENT "<%= @feepayment.feepayment_code %>"</h3>

<div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>DESCRIPTION</th>
            <th>VALUE</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>CODE OF THIS FEE PAYMENT:</td>
            <td><%= @feepayment.feepayment_code %></td>
          </tr>
          <tr>
            <td>DATE OF PAYMENT:</td>
            <td><%= @feepayment.date_of_payment %></td>
          </tr>
          <tr>
            <td>AMOUNT OF PAYMENT:</td>
            <td><%= @feepayment.amount_of_payment %></td>
          </tr>
          <tr>
            <td>STUDENT NAME:</td>
            <td><%= @feepayment.name_of_student %></td>
          </tr>       
      </tbody>
    </table>
  </div>
  <br>
  <br>

<table class="center">
      <thead>
        <tr>
            <th><%= link_to "DELETE", @feepayment, method: :delete, data: { confirm: "Really want to DELETE this Fee Payment #{@feepayment.to_s}?" } %></th>
            <th><%= link_to "UPDATE", edit_feepayment_path(@feepayment) %></th>
            <th><%= link_to "BACK", feepayments_path %></th>
        </tr>
      </thead>
</table>