config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :classrooms
  resources :salarypayments
  resources :feepayments
  resources :salaries
  resources :tuitionfees
  resources :users

  root 'welcome#home'
  # root 'welcome#login'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  
  # get '/auth/github/callback' => 'sessions#create'

  # get '/auth/developer/callback' => 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/salarypayment.rb
class Salarypayment < ApplicationRecord
  belongs_to :teacher

  def to_s
    return self.salarypayment_code
  end

  def name_of_teacher
    self.teacher.teacher_name
  end

end

app/controllers/salarypayments_controller.rb
class SalarypaymentsController < ApplicationController

    def index
		@salarypayments = Salarypayment.all
	end

    def new
        @salarypayment = Salarypayment.new
    end
  
    def create
        @salarypayment = Salarypayment.new(salarypayment_params)
        if @salarypayment.save
        redirect_to salarypayment_path(@salarypayment)
       else
        render :new
       end
    end
  
    def show
        @salarypayment = Salarypayment.find(params[:id])
    end
  
     
    def edit
        @salarypayment = Salarypayment.find(params[:id])
    end
  
    def update
        @salarypayment = Salarypayment.find(params[:id])
        if @salarypayment.update(salarypayment_params)
        redirect_to salarypayment_path(@salarypayment)
        else
            render :edit
        end
    end

    def destroy
        Salarypayment.find(params[:id]).destroy
        redirect_to action: "index"
    end
  
    private
  
    def salarypayment_params
        params.require(:salarypayment).permit(:id, :salarypayment_code, :date_of_payment, :amount_of_payment, :teacher_id)
    end

    def teacher_params
        params.require(:teacher).permit(:salary_id)
    end
end

app/helpers/salarypayments_helper.rb
module SalarypaymentsHelper
end

app/views/salarypayments/edit.html.erb
    <%= render "layouts/header" %>  
<div class="center">

<h1>Updating a SALARY PAYMENT</h1>
<%= form_for(@salarypayment) do |f| %>
  <label>Salary Payment Code:</label><br>
  <%= f.text_field :salarypayment_code %><br>

  <label>Date of Payment</label><br>
  <%= f.text_area :date_of_payment %><br>

  <label>Amount of Payment</label><br>
  <%= f.text_area :amount_of_payment %><br>

    <label>TEACHER NAME</label><br>
  <%= f.collection_select :teacher, Teacher.all, :id, :teacher_name, { include_blank: false }, { class: "collectionselect" } %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/salarypayments/index.html.erb
    <%= render "layouts/header" %>    
  
  <h1 class="center">All Salary Payment Categories</h1>

  <div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>SALARY PAYMENT ID</th>
            <th>SALARY PAYMENT CODE</th>
            <th>DATE OF PAYMENT</th>
            <th>AMOUNT OF PAYMENT</th>
            <th>TEACHER NAME</th>         
            <th>DETAILS/UPDATE/DELETE</th>
        </tr>
      </thead>
      <tbody>
        <% @salarypayments.each do |amount| %>
          <tr>
            <td><%= amount.id %></td>
            <td><%= amount.salarypayment_code %></td>
            <td><%= amount.date_of_payment %></td>
            <td><%= amount.amount_of_payment %></td>
            <td><%= amount.name_of_teacher %></td>         
            <td><%= link_to "DETAILS/UPDATE/DELETE", salarypayment_path(amount) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
<br>
<table class="center">
      <thead>
        <tr>
          <th><%= link_to "+ Create Salary Payment", new_salarypayment_path %></th>
        </tr>
      </thead>
</table>

app/views/salarypayments/new.html.erb
    <%= render "layouts/header" %>  
<div class="center">
<h1>Recording a NEW SALARY PAYMENT</h1>
<%= form_for(@salarypayment) do |f| %>
  <label>Salary Payment Code:</label><br>
  <%= f.text_field :salarypayment_code %><br>

  <label>Date of Payment</label><br>
  <%= f.text_area :date_of_payment %><br>

  <label>Amount of Payment</label><br>
  <%= f.text_area :amount_of_payment %><br>

    <label>TEACHER NAME</label><br>
  <%= f.collection_select :teacher, Teacher.all, :id, :teacher_name, { include_blank: false }, { class: "collectionselect" } %><br>

  <%= f.submit %>
<% end %>

</div>

app/views/salarypayments/show.html.erb
    <%= render "layouts/header" %>  

<h3 class="center"> FOLLOWING ARE THE DETAILS OF SALARY PAYMENT "<%= @salarypayment.salarypayment_code %>"</h3>

<div class='main-centre tableFixHead'>
    <table class="center">
      <thead>
        <tr>
            <th>DESCRIPTION</th>
            <th>VALUE</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>CODE OF THIS SALARY PAYMENT:</td>
            <td><%= @salarypayment.salarypayment_code %></td>
          </tr>
          <tr>
          <td>DATE OF PAYMENT:</td>
          <td><%= @salarypayment.date_of_payment %></td>
          </tr>
          <tr>
          <td>AMOUNT OF PAYMENT:</td>
          <td><%= @salarypayment.amount_of_payment %></td>
          </tr>
          <tr>
          <td>TEACHER NAME:</td>
          <td><%= @salarypayment.name_of_teacher %></td>
          </tr>

      </tbody>
    </table>
  </div>
  <br>
  <br>

<table class="center">
      <thead>
        <tr>
            <th><%= link_to "DELETE", @salarypayment, method: :delete, data: { confirm: "Really want to DELETE the TuitionFee category #{@salarypayment.to_s}?" } %></th>
            <th><%= link_to "UPDATE", edit_salarypayment_path(@salarypayment) %></th>
            <th><%= link_to "BACK", salarypayments_path %></th>
        </tr>
      </thead>
</table>